image: node:12.16.1

include:
  - template: License-Scanning.gitlab-ci.yml

test:
  before_script:
    - npm i
    - cd src/util
    - node findandedit.js
    - cd ../
  script:
    - npm test --debugToken=$DEBUG_TOKEN --googleAPIKey=$GOOGLE_API_KEY