image: node:12.16.3-stretch

include:
  - template: License-Scanning.gitlab-ci.yml

test:
  before_script:
    - npm run build
    - npm i --build-from-source --verbose
    - cd src/util
    - node findandedit.js
    - cd ../
  script:
    - npm test --debugToken=$DEBUG_TOKEN --googleAPIKey=$GOOGLE_API_KEY